os: linux
dist: xenial
language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
script: 
- make checkfmt
- make fmt  
- make vet 
- make race
- make gocyclo
- make lint 
- make ineffassign
- make misspell
- make test
- make benchmark
- make coverage
- bash <(curl -s https://codecov.io/bash)